/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
    compileOnly(project(":common"))
    //system("me.minebuilders:clearlag:3.2.2")
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-Clearlag"

java {
    withJavadocJar()
}
