/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly(project(":quickshop-platform-interface"))
    api("com.github.PikaMug:LocaleLib:3.1")
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
    compileOnly("commons-lang:commons-lang:2.6")
}

description = "quickshop-platform-spigot-abstract"

java {
    withJavadocJar()
}
