/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
    compileOnly("com.palmergames.bukkit.towny:towny:0.98.4.20")
    compileOnly(project(":common"))
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-Towny"

java {
    withJavadocJar()
}
