/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.0.7")
    compileOnly(project(":common"))
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-WorldGuard"

java {
    withJavadocJar()
}
