/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly(project(":quickshop-bukkit"))
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
}

group = "com.ghostchu.quickshop.compatibility"
description = "quickshop-compatibility-common"

java {
    withJavadocJar()
}
