/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly("org.apache.commons:commons-lang3:3.12.0")
    compileOnly("org.slf4j:slf4j-jdk14:2.0.6")
    compileOnly("com.google.code.gson:gson:2.10.1")
    api("net.kyori:adventure-platform-bukkit:4.2.0")
    api("net.kyori:adventure-text-minimessage:4.12.0")
    api("net.kyori:adventure-text-serializer-plain:4.12.0")
    api("net.kyori:adventure-text-serializer-legacy:4.12.0")
    api("net.kyori:adventure-text-serializer-gson:4.12.0")
    compileOnly("com.vdurmont:semver4j:3.1.0")
}

description = "quickshop-common"

java {
    withJavadocJar()
}
