/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
    compileOnly(project(":common"))
    //system("zrips.residence:Residence:5.0.1.7")
    //system("zrips.cmilib:CMILib:1.2.2.0")
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-Residence"

java {
    withJavadocJar()
}
