/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.19.3-R0.1-SNAPSHOT")
    compileOnly("com.discordsrv:discordsrv:1.26.0")
    compileOnly(project(":quickshop-bukkit"))
}

group = "com.ghostchu.quickshop.addon"
description = "Addon-DiscordSRV"

java {
    withJavadocJar()
}
