/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
    compileOnly(project(":quickshop-bukkit"))
}

group = "com.ghostchu.quickshop.addon"
description = "Addon-Limited"

java {
    withJavadocJar()
}
