/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    api(project(":quickshop-common"))
    api("cc.carm.lib:easysql-hikaricp:0.4.6")
    api("com.ghostchu:simplereloadlib:1.1.2")
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
}

description = "quickshop-api"

java {
    withJavadocJar()
}
