/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
    compileOnly("com.github.jikoo.OpenInv:openinvapi:4.2.2")
    compileOnly(project(":common"))
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-OpenInv"

java {
    withJavadocJar()
}
