/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ghostchu.java-conventions")
}

dependencies {
    api(project(":quickshop-api"))
    api(project(":quickshop-platform-interface"))
    api(project(":quickshop-platform-spigot-abstract"))
    api(project(":quickshop-platform-spigot-v1_18_R1"))
    api(project(":quickshop-platform-spigot-v1_18_R2"))
    api(project(":quickshop-platform-spigot-v1_19_R1"))
    api(project(":quickshop-platform-spigot-v1_19_R2"))
    api(project(":quickshop-platform-paper"))
    // The dependencies below are resolved by Spigot Library Loader
    compileOnly("org.apache.commons:commons-compress:1.22")
    compileOnly("org.apache.commons:commons-text:1.10.0")
    compileOnly("com.rollbar:rollbar-java:1.9.0")
    compileOnly("commons-codec:commons-codec:1.15")
    compileOnly("io.papermc:paperlib:1.0.7")
    compileOnly("com.h2database:h2:2.1.214")
    compileOnly("com.konghq:unirest-java:3.14.1")
    compileOnly("com.dumptruckman.minecraft:JsonConfiguration:1.1")
    compileOnly("net.minidev:json-smart:1.3.3")
    compileOnly("com.github.juliomarcopineda:jdbc-stream:0.1.1")
    compileOnly("de.themoep:minedown-adventure:1.7.2-SNAPSHOT")
    compileOnly("net.sourceforge.csvjdbc:csvjdbc:1.0.40")
    compileOnly("org.dom4j:dom4j:2.1.3")
    compileOnly("com.ghostchu.crowdin:crowdinota:1.0.3")
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
    compileOnly("com.comphenix.protocol:ProtocolLib:5.0.0-SNAPSHOT")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7.1")
    compileOnly("me.clip:placeholderapi:2.11.2")
    compileOnly("net.tnemc:Reserve:0.1.5.3-SNAPSHOT-4")
    compileOnly("net.essentialsx:EssentialsX:2.19.7")
    compileOnly(fileTree("lib") { include("*.jar") })
}

description = "QuickShop-Hikari"

java {
    withJavadocJar()
}
